FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.11_9
COPY target/school-reg-system-0.0.1-SNAPSHOT.jar school-reg-system-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/school-reg-system-0.0.1-SNAPSHOT.jar"]